package com.woowla.compose.icon.collections.devicons.devicons.trpc

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.PathFillType.Companion.NonZero
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.woowla.compose.icon.collections.devicons.devicons.TrpcGroup

public val TrpcGroup.OriginalWordmark: ImageVector
    get() {
        if (_originalWordmark != null) {
            return _originalWordmark!!
        }
        _originalWordmark = Builder(name = "OriginalWordmark", defaultWidth = 128.0.dp,
                defaultHeight = 128.0.dp, viewportWidth = 128.0f, viewportHeight = 128.0f).apply {
            path(fill = SolidColor(Color(0xFF398ccb)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = NonZero) {
                moveTo(0.3f, 56.0f)
                curveToRelative(0.0f, -6.1f, 4.9f, -11.0f, 11.0f, -11.0f)
                horizontalLineToRelative(16.2f)
                curveToRelative(6.1f, 0.0f, 11.0f, 4.9f, 11.0f, 11.0f)
                verticalLineToRelative(16.0f)
                curveToRelative(0.0f, 6.1f, -4.9f, 11.0f, -11.0f, 11.0f)
                horizontalLineTo(11.3f)
                curveToRelative(-6.1f, 0.0f, -11.0f, -4.9f, -11.0f, -11.0f)
                close()
            }
            path(fill = SolidColor(Color(0xFF000000)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = NonZero) {
                moveToRelative(19.4f, 50.6f)
                lineToRelative(5.3f, 3.0f)
                verticalLineToRelative(1.7f)
                lineToRelative(6.4f, 3.7f)
                verticalLineToRelative(6.3f)
                lineToRelative(1.7f, 1.0f)
                verticalLineToRelative(6.1f)
                lineToRelative(-5.3f, 3.0f)
                lineToRelative(-2.4f, -1.4f)
                lineToRelative(-5.7f, 3.3f)
                lineToRelative(-5.7f, -3.2f)
                lineToRelative(-2.3f, 1.3f)
                lineToRelative(-5.3f, -3.0f)
                verticalLineToRelative(-6.1f)
                lineToRelative(1.7f, -1.0f)
                lineTo(7.8f, 59.0f)
                lineToRelative(6.3f, -3.6f)
                verticalLineToRelative(-1.8f)
                close()
                moveTo(24.7f, 56.9f)
                verticalLineToRelative(2.8f)
                lineToRelative(-5.3f, 3.1f)
                lineToRelative(-5.3f, -3.1f)
                lineTo(14.1f, 57.0f)
                lineToRelative(-4.9f, 2.8f)
                verticalLineToRelative(4.8f)
                lineToRelative(2.2f, -1.3f)
                lineToRelative(5.3f, 3.0f)
                verticalLineToRelative(6.1f)
                lineToRelative(-1.6f, 0.9f)
                lineToRelative(4.3f, 2.5f)
                lineToRelative(4.4f, -2.5f)
                lineToRelative(-1.6f, -0.9f)
                verticalLineToRelative(-6.1f)
                lineToRelative(5.3f, -3.0f)
                lineToRelative(2.2f, 1.2f)
                verticalLineToRelative(-4.7f)
                close()
                moveTo(26.9f, 73.5f)
                verticalLineToRelative(-3.8f)
                lineToRelative(-3.3f, -1.8f)
                verticalLineToRelative(3.7f)
                close()
                moveTo(31.5f, 67.9f)
                lineTo(28.3f, 69.8f)
                verticalLineToRelative(3.7f)
                lineToRelative(3.2f, -1.9f)
                close()
                moveTo(10.8f, 73.5f)
                verticalLineToRelative(-3.7f)
                lineToRelative(-3.2f, -1.9f)
                verticalLineToRelative(3.8f)
                close()
                moveTo(15.4f, 67.9f)
                lineTo(12.2f, 69.7f)
                verticalLineToRelative(3.8f)
                lineToRelative(3.2f, -1.9f)
                close()
                moveTo(27.6f, 68.6f)
                lineTo(30.8f, 66.7f)
                lineTo(27.6f, 64.9f)
                lineTo(24.3f, 66.7f)
                close()
                moveTo(11.6f, 64.9f)
                lineTo(8.3f, 66.8f)
                lineTo(11.6f, 68.6f)
                lineTo(14.8f, 66.8f)
                close()
                moveTo(18.8f, 60.8f)
                verticalLineToRelative(-3.7f)
                lineToRelative(-3.2f, -1.8f)
                lineTo(15.6f, 59.0f)
                close()
                moveTo(23.4f, 55.2f)
                lineTo(20.2f, 57.1f)
                verticalLineToRelative(3.7f)
                lineToRelative(3.2f, -1.9f)
                close()
                moveTo(19.5f, 55.9f)
                lineTo(22.7f, 54.0f)
                lineTo(19.5f, 52.2f)
                lineTo(16.3f, 54.0f)
                close()
                moveTo(45.1f, 57.6f)
                horizontalLineToRelative(12.4f)
                verticalLineToRelative(4.6f)
                lineTo(45.1f, 62.2f)
                close()
                moveTo(47.7f, 52.9f)
                horizontalLineToRelative(6.2f)
                verticalLineToRelative(18.0f)
                quadToRelative(0.0f, 0.6f, 0.2f, 0.9f)
                quadToRelative(0.2f, 0.4f, 0.6f, 0.5f)
                quadToRelative(0.3f, 0.2f, 0.8f, 0.2f)
                quadToRelative(0.4f, 0.0f, 0.8f, -0.1f)
                reflectiveQuadToRelative(0.6f, -0.1f)
                lineToRelative(0.9f, 4.4f)
                quadToRelative(-0.4f, 0.2f, -1.3f, 0.4f)
                quadToRelative(-0.8f, 0.1f, -1.9f, 0.2f)
                quadToRelative(-2.2f, 0.1f, -3.7f, -0.5f)
                quadToRelative(-1.6f, -0.6f, -2.4f, -1.9f)
                quadToRelative(-0.8f, -1.3f, -0.8f, -3.3f)
                close()
                moveTo(59.6f, 77.0f)
                lineTo(59.6f, 51.1f)
                horizontalLineToRelative(10.8f)
                quadToRelative(2.9f, 0.0f, 5.0f, 1.0f)
                quadToRelative(2.2f, 1.1f, 3.3f, 3.0f)
                quadToRelative(1.2f, 1.9f, 1.2f, 4.6f)
                quadToRelative(0.0f, 2.7f, -1.2f, 4.6f)
                quadToRelative(-1.2f, 1.8f, -3.4f, 2.8f)
                quadToRelative(-2.1f, 1.0f, -5.1f, 1.0f)
                horizontalLineToRelative(-6.8f)
                verticalLineToRelative(-4.9f)
                lineTo(69.0f, 63.2f)
                quadToRelative(1.4f, 0.0f, 2.4f, -0.4f)
                reflectiveQuadToRelative(1.4f, -1.1f)
                quadToRelative(0.5f, -0.8f, 0.5f, -2.0f)
                reflectiveQuadToRelative(-0.5f, -2.0f)
                quadToRelative(-0.4f, -0.8f, -1.4f, -1.2f)
                quadToRelative(-1.0f, -0.4f, -2.4f, -0.4f)
                horizontalLineToRelative(-3.1f)
                lineTo(65.9f, 77.0f)
                close()
                moveTo(74.3f, 65.1f)
                lineTo(80.7f, 77.0f)
                horizontalLineToRelative(-6.8f)
                lineToRelative(-6.4f, -11.9f)
                close()
                moveTo(81.9f, 77.0f)
                lineTo(81.9f, 51.1f)
                horizontalLineToRelative(10.8f)
                quadToRelative(2.9f, 0.0f, 5.0f, 1.1f)
                quadToRelative(2.2f, 1.1f, 3.3f, 3.2f)
                quadToRelative(1.2f, 2.0f, 1.2f, 4.6f)
                quadToRelative(0.0f, 2.7f, -1.2f, 4.7f)
                reflectiveQuadToRelative(-3.3f, 3.1f)
                quadToRelative(-2.2f, 1.1f, -5.2f, 1.1f)
                horizontalLineToRelative(-6.6f)
                lineTo(85.9f, 64.0f)
                horizontalLineToRelative(5.4f)
                quadToRelative(1.5f, 0.0f, 2.4f, -0.5f)
                quadToRelative(1.0f, -0.5f, 1.5f, -1.4f)
                quadToRelative(0.5f, -0.9f, 0.5f, -2.1f)
                quadToRelative(0.0f, -1.2f, -0.5f, -2.0f)
                quadToRelative(-0.5f, -0.9f, -1.5f, -1.4f)
                quadToRelative(-1.0f, -0.5f, -2.4f, -0.5f)
                horizontalLineToRelative(-3.1f)
                lineTo(88.2f, 77.0f)
                close()
                moveTo(127.5f, 60.5f)
                horizontalLineToRelative(-6.4f)
                quadToRelative(-0.1f, -1.0f, -0.5f, -1.8f)
                reflectiveQuadToRelative(-1.0f, -1.3f)
                quadToRelative(-0.7f, -0.6f, -1.6f, -0.9f)
                quadToRelative(-0.8f, -0.3f, -1.9f, -0.3f)
                quadToRelative(-1.9f, 0.0f, -3.3f, 0.9f)
                quadToRelative(-1.3f, 1.0f, -2.1f, 2.7f)
                quadToRelative(-0.7f, 1.7f, -0.7f, 4.2f)
                quadToRelative(0.0f, 2.6f, 0.7f, 4.3f)
                quadToRelative(0.8f, 1.8f, 2.1f, 2.7f)
                quadToRelative(1.4f, 0.8f, 3.3f, 0.8f)
                quadToRelative(1.0f, 0.0f, 1.8f, -0.2f)
                quadToRelative(0.9f, -0.3f, 1.6f, -0.8f)
                quadToRelative(0.6f, -0.5f, 1.0f, -1.2f)
                quadToRelative(0.5f, -0.8f, 0.6f, -1.7f)
                horizontalLineToRelative(6.4f)
                quadToRelative(-0.2f, 1.7f, -1.0f, 3.4f)
                reflectiveQuadToRelative(-2.3f, 3.0f)
                quadToRelative(-1.4f, 1.4f, -3.5f, 2.2f)
                quadToRelative(-2.1f, 0.8f, -4.8f, 0.8f)
                quadToRelative(-3.5f, 0.0f, -6.3f, -1.5f)
                quadToRelative(-2.8f, -1.6f, -4.4f, -4.5f)
                quadToRelative(-1.6f, -3.0f, -1.6f, -7.3f)
                reflectiveQuadToRelative(1.6f, -7.2f)
                quadToRelative(1.7f, -3.0f, 4.5f, -4.5f)
                quadToRelative(2.8f, -1.6f, 6.2f, -1.6f)
                quadToRelative(2.4f, 0.0f, 4.4f, 0.7f)
                quadToRelative(2.0f, 0.6f, 3.5f, 1.9f)
                quadToRelative(1.6f, 1.2f, 2.5f, 3.0f)
                quadToRelative(1.0f, 1.8f, 1.2f, 4.2f)
                close()
            }
        }
        .build()
        return _originalWordmark!!
    }

private var _originalWordmark: ImageVector? = null
