package com.woowla.compose.icon.collections.simpleicons.simpleicons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType.Companion.NonZero
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.woowla.compose.icon.collections.simpleicons.Simpleicons

public val Simpleicons.Vencord: ImageVector
    get() {
        if (_vencord != null) {
            return _vencord!!
        }
        _vencord = Builder(name = "Vencord", defaultWidth = 24.0.dp, defaultHeight = 24.0.dp,
                viewportWidth = 24.0f, viewportHeight = 24.0f).apply {
            path(fill = SolidColor(Color(0xFF000000)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = NonZero) {
                moveTo(0.613f, 0.6f)
                verticalLineToRelative(0.587f)
                horizontalLineToRelative(2.4f)
                lineTo(3.013f, 0.6f)
                horizontalLineToRelative(-1.2f)
                close()
                moveTo(3.013f, 1.187f)
                verticalLineToRelative(8.4f)
                lineTo(3.6f, 9.587f)
                verticalLineToRelative(-8.4f)
                horizontalLineToRelative(-0.293f)
                close()
                moveTo(3.6f, 9.587f)
                verticalLineToRelative(0.613f)
                horizontalLineToRelative(0.613f)
                verticalLineToRelative(-0.613f)
                horizontalLineToRelative(-0.306f)
                close()
                moveTo(4.213f, 10.2f)
                verticalLineToRelative(0.587f)
                lineTo(4.8f, 10.787f)
                lineTo(4.8f, 10.2f)
                horizontalLineToRelative(-0.293f)
                close()
                moveTo(4.8f, 10.787f)
                verticalLineToRelative(0.613f)
                horizontalLineToRelative(0.613f)
                verticalLineToRelative(-0.613f)
                horizontalLineToRelative(-0.306f)
                close()
                moveTo(5.413f, 11.4f)
                verticalLineToRelative(0.587f)
                lineTo(6.0f, 11.987f)
                lineTo(6.0f, 11.4f)
                horizontalLineToRelative(-0.293f)
                close()
                moveTo(6.0f, 11.987f)
                verticalLineToRelative(0.613f)
                horizontalLineToRelative(1.2f)
                verticalLineToRelative(-0.613f)
                horizontalLineToRelative(-0.6f)
                close()
                moveTo(7.2f, 11.987f)
                horizontalLineToRelative(0.613f)
                lineTo(7.813f, 11.4f)
                lineTo(7.2f, 11.4f)
                verticalLineToRelative(0.293f)
                close()
                moveTo(7.813f, 11.4f)
                lineTo(8.4f, 11.4f)
                lineTo(8.4f, 15.0f)
                horizontalLineToRelative(-0.587f)
                verticalLineToRelative(0.587f)
                lineTo(8.4f, 15.587f)
                verticalLineToRelative(4.8f)
                horizontalLineToRelative(0.613f)
                verticalLineToRelative(-9.6f)
                horizontalLineToRelative(2.4f)
                verticalLineToRelative(-2.4f)
                lineTo(10.8f, 8.387f)
                lineTo(10.8f, 10.2f)
                lineTo(9.6f, 10.2f)
                verticalLineToRelative(-0.613f)
                horizontalLineToRelative(-0.587f)
                verticalLineToRelative(0.613f)
                lineTo(8.4f, 10.2f)
                verticalLineToRelative(0.587f)
                horizontalLineToRelative(-0.587f)
                verticalLineToRelative(0.306f)
                close()
                moveTo(9.6f, 9.587f)
                horizontalLineToRelative(0.613f)
                verticalLineToRelative(-8.4f)
                lineTo(9.6f, 1.187f)
                verticalLineToRelative(4.2f)
                close()
                moveTo(10.213f, 1.187f)
                horizontalLineToRelative(2.4f)
                lineTo(12.613f, 0.6f)
                horizontalLineToRelative(-2.4f)
                verticalLineToRelative(0.293f)
                close()
                moveTo(12.613f, 1.187f)
                lineTo(12.613f, 7.8f)
                horizontalLineToRelative(-1.2f)
                verticalLineToRelative(0.587f)
                lineTo(15.6f, 8.387f)
                verticalLineToRelative(0.32f)
                lineTo(18.0f, 8.707f)
                verticalLineToRelative(-0.32f)
                horizontalLineToRelative(0.614f)
                verticalLineToRelative(0.32f)
                horizontalLineToRelative(2.106f)
                verticalLineToRelative(-0.32f)
                horizontalLineToRelative(0.294f)
                lineTo(21.014f, 6.893f)
                horizontalLineToRelative(-0.294f)
                verticalLineToRelative(-0.906f)
                horizontalLineToRelative(-0.32f)
                verticalLineToRelative(-0.88f)
                horizontalLineToRelative(-0.293f)
                lineTo(20.107f, 5.4f)
                horizontalLineToRelative(-0.293f)
                verticalLineToRelative(0.907f)
                horizontalLineToRelative(-0.294f)
                lineTo(19.52f, 6.6f)
                horizontalLineToRelative(0.294f)
                verticalLineToRelative(0.587f)
                horizontalLineToRelative(0.293f)
                verticalLineToRelative(-0.88f)
                horizontalLineToRelative(0.293f)
                verticalLineToRelative(0.88f)
                horizontalLineToRelative(0.32f)
                verticalLineToRelative(0.906f)
                horizontalLineToRelative(-0.32f)
                verticalLineToRelative(0.294f)
                horizontalLineToRelative(-0.586f)
                verticalLineToRelative(-0.294f)
                horizontalLineToRelative(0.293f)
                lineTo(20.107f, 7.8f)
                horizontalLineToRelative(0.293f)
                verticalLineToRelative(-0.613f)
                horizontalLineToRelative(-0.293f)
                verticalLineToRelative(0.32f)
                horizontalLineToRelative(-0.293f)
                lineTo(19.814f, 7.8f)
                horizontalLineToRelative(-0.294f)
                verticalLineToRelative(0.587f)
                horizontalLineToRelative(-0.613f)
                lineTo(18.907f, 7.8f)
                horizontalLineToRelative(-0.293f)
                verticalLineToRelative(-0.293f)
                horizontalLineToRelative(-0.294f)
                lineTo(18.32f, 7.8f)
                horizontalLineToRelative(-1.813f)
                verticalLineToRelative(0.293f)
                horizontalLineToRelative(1.2f)
                verticalLineToRelative(0.294f)
                lineTo(15.92f, 8.387f)
                verticalLineToRelative(-0.294f)
                horizontalLineToRelative(-1.813f)
                lineTo(14.107f, 7.8f)
                horizontalLineToRelative(-0.293f)
                lineTo(13.814f, 6.307f)
                horizontalLineToRelative(-0.294f)
                lineTo(13.52f, 7.8f)
                horizontalLineToRelative(-0.32f)
                lineTo(13.2f, 1.187f)
                horizontalLineToRelative(-0.293f)
                close()
                moveTo(13.813f, 6.307f)
                horizontalLineToRelative(0.294f)
                verticalLineToRelative(-0.32f)
                horizontalLineToRelative(-0.294f)
                verticalLineToRelative(0.16f)
                close()
                moveTo(14.107f, 5.987f)
                horizontalLineToRelative(0.293f)
                lineTo(14.4f, 5.4f)
                horizontalLineToRelative(-0.293f)
                verticalLineToRelative(0.293f)
                close()
                moveTo(14.4f, 5.4f)
                horizontalLineToRelative(0.614f)
                verticalLineToRelative(-0.293f)
                lineTo(14.4f, 5.107f)
                verticalLineToRelative(0.146f)
                close()
                moveTo(15.014f, 5.107f)
                horizontalLineToRelative(0.586f)
                lineTo(15.6f, 5.4f)
                horizontalLineToRelative(0.32f)
                verticalLineToRelative(-0.613f)
                horizontalLineToRelative(-0.906f)
                verticalLineToRelative(0.16f)
                close()
                moveTo(15.92f, 4.787f)
                horizontalLineToRelative(0.293f)
                verticalLineToRelative(-0.294f)
                horizontalLineToRelative(-0.293f)
                verticalLineToRelative(0.147f)
                close()
                moveTo(16.213f, 4.493f)
                horizontalLineToRelative(0.294f)
                lineTo(16.507f, 4.2f)
                horizontalLineToRelative(-0.294f)
                verticalLineToRelative(0.147f)
                close()
                moveTo(16.507f, 4.2f)
                horizontalLineToRelative(0.293f)
                verticalLineToRelative(-0.293f)
                horizontalLineToRelative(-0.293f)
                verticalLineToRelative(0.146f)
                close()
                moveTo(16.8f, 4.2f)
                verticalLineToRelative(0.587f)
                horizontalLineToRelative(0.32f)
                verticalLineToRelative(0.32f)
                horizontalLineToRelative(0.293f)
                verticalLineToRelative(-0.32f)
                horizontalLineToRelative(0.294f)
                verticalLineToRelative(0.32f)
                horizontalLineToRelative(-0.294f)
                lineTo(17.413f, 5.4f)
                lineTo(18.0f, 5.4f)
                verticalLineToRelative(-0.613f)
                horizontalLineToRelative(0.32f)
                lineTo(18.32f, 4.2f)
                lineTo(18.0f, 4.2f)
                verticalLineToRelative(0.293f)
                horizontalLineToRelative(-0.88f)
                lineTo(17.12f, 4.2f)
                horizontalLineToRelative(-0.16f)
                close()
                moveTo(18.32f, 4.2f)
                horizontalLineToRelative(0.294f)
                verticalLineToRelative(-0.293f)
                horizontalLineToRelative(-0.294f)
                verticalLineToRelative(0.146f)
                close()
                moveTo(18.614f, 3.907f)
                horizontalLineToRelative(0.293f)
                verticalLineToRelative(-0.32f)
                horizontalLineToRelative(-0.293f)
                verticalLineToRelative(0.16f)
                close()
                moveTo(18.907f, 3.587f)
                horizontalLineToRelative(0.293f)
                verticalLineToRelative(-0.294f)
                horizontalLineToRelative(-0.293f)
                verticalLineToRelative(0.147f)
                close()
                moveTo(19.2f, 3.587f)
                verticalLineToRelative(1.52f)
                horizontalLineToRelative(0.32f)
                verticalLineToRelative(-0.32f)
                horizontalLineToRelative(0.293f)
                verticalLineToRelative(-0.294f)
                horizontalLineToRelative(-0.293f)
                verticalLineToRelative(-0.906f)
                horizontalLineToRelative(-0.16f)
                close()
                moveTo(19.813f, 4.787f)
                verticalLineToRelative(0.32f)
                horizontalLineToRelative(0.294f)
                verticalLineToRelative(-0.32f)
                horizontalLineToRelative(-0.147f)
                close()
                moveTo(19.813f, 5.107f)
                horizontalLineToRelative(-0.293f)
                lineTo(19.52f, 5.4f)
                horizontalLineToRelative(0.293f)
                verticalLineToRelative(-0.147f)
                close()
                moveTo(15.6f, 5.4f)
                horizontalLineToRelative(-0.293f)
                verticalLineToRelative(1.2f)
                horizontalLineToRelative(0.293f)
                lineTo(15.6f, 6.0f)
                close()
                moveTo(15.6f, 6.6f)
                verticalLineToRelative(0.587f)
                horizontalLineToRelative(0.32f)
                lineTo(15.92f, 6.6f)
                horizontalLineToRelative(-0.16f)
                close()
                moveTo(15.92f, 7.187f)
                verticalLineToRelative(0.32f)
                horizontalLineToRelative(0.293f)
                verticalLineToRelative(-0.32f)
                horizontalLineToRelative(-0.146f)
                close()
                moveTo(16.213f, 7.507f)
                lineTo(16.213f, 7.8f)
                horizontalLineToRelative(0.294f)
                verticalLineToRelative(-0.293f)
                horizontalLineToRelative(-0.147f)
                close()
                moveTo(18.907f, 7.8f)
                horizontalLineToRelative(0.613f)
                verticalLineToRelative(-0.293f)
                horizontalLineToRelative(-0.613f)
                verticalLineToRelative(0.146f)
                close()
                moveTo(19.52f, 7.507f)
                horizontalLineToRelative(0.293f)
                verticalLineToRelative(-0.32f)
                horizontalLineToRelative(-0.293f)
                verticalLineToRelative(0.16f)
                close()
                moveTo(19.52f, 6.6f)
                horizontalLineToRelative(-0.613f)
                verticalLineToRelative(0.293f)
                horizontalLineToRelative(0.613f)
                verticalLineToRelative(-0.146f)
                close()
                moveTo(18.907f, 6.893f)
                horizontalLineToRelative(-0.293f)
                verticalLineToRelative(0.294f)
                horizontalLineToRelative(0.293f)
                lineTo(18.907f, 7.04f)
                close()
                moveTo(21.014f, 8.387f)
                verticalLineToRelative(2.4f)
                horizontalLineToRelative(2.4f)
                lineTo(23.414f, 10.2f)
                lineTo(21.6f, 10.2f)
                lineTo(21.6f, 8.387f)
                horizontalLineToRelative(-0.293f)
                close()
                moveTo(23.414f, 10.787f)
                verticalLineToRelative(2.4f)
                lineTo(24.0f, 13.187f)
                verticalLineToRelative(-2.4f)
                horizontalLineToRelative(-0.293f)
                close()
                moveTo(23.414f, 13.187f)
                horizontalLineToRelative(-4.8f)
                verticalLineToRelative(0.613f)
                horizontalLineToRelative(4.8f)
                verticalLineToRelative(-0.307f)
                close()
                moveTo(18.614f, 13.187f)
                verticalLineToRelative(-2.4f)
                horizontalLineToRelative(-4.8f)
                verticalLineToRelative(9.6f)
                horizontalLineToRelative(4.8f)
                verticalLineToRelative(-2.4f)
                lineTo(18.0f, 17.987f)
                lineTo(18.0f, 19.8f)
                horizontalLineToRelative(-3.6f)
                verticalLineToRelative(-8.4f)
                lineTo(18.0f, 11.4f)
                verticalLineToRelative(1.787f)
                horizontalLineToRelative(0.307f)
                close()
                moveTo(18.614f, 17.987f)
                horizontalLineToRelative(4.8f)
                lineTo(23.414f, 17.4f)
                horizontalLineToRelative(-4.8f)
                verticalLineToRelative(0.293f)
                close()
                moveTo(23.414f, 17.987f)
                verticalLineToRelative(2.4f)
                lineTo(24.0f, 20.387f)
                verticalLineToRelative(-2.4f)
                horizontalLineToRelative(-0.293f)
                close()
                moveTo(23.414f, 20.387f)
                horizontalLineToRelative(-2.4f)
                verticalLineToRelative(2.4f)
                horizontalLineToRelative(0.586f)
                lineTo(21.6f, 21.0f)
                horizontalLineToRelative(1.814f)
                verticalLineToRelative(-0.306f)
                close()
                moveTo(21.014f, 22.787f)
                horizontalLineToRelative(-9.6f)
                verticalLineToRelative(0.613f)
                horizontalLineToRelative(9.6f)
                verticalLineToRelative(-0.307f)
                close()
                moveTo(11.414f, 22.787f)
                verticalLineToRelative(-2.4f)
                horizontalLineToRelative(-2.4f)
                lineTo(9.014f, 21.0f)
                lineTo(10.8f, 21.0f)
                verticalLineToRelative(1.787f)
                horizontalLineToRelative(0.307f)
                close()
                moveTo(7.814f, 15.587f)
                horizontalLineToRelative(-2.4f)
                verticalLineToRelative(0.613f)
                horizontalLineToRelative(2.4f)
                verticalLineToRelative(-0.307f)
                close()
                moveTo(5.414f, 15.587f)
                lineTo(5.414f, 15.0f)
                lineTo(4.8f, 15.0f)
                verticalLineToRelative(0.587f)
                horizontalLineToRelative(0.307f)
                close()
                moveTo(4.8f, 15.0f)
                verticalLineToRelative(-0.613f)
                horizontalLineToRelative(-0.586f)
                lineTo(4.214f, 15.0f)
                horizontalLineToRelative(0.293f)
                close()
                moveTo(4.214f, 14.387f)
                lineTo(4.214f, 13.8f)
                lineTo(3.6f, 13.8f)
                verticalLineToRelative(0.587f)
                horizontalLineToRelative(0.307f)
                close()
                moveTo(3.6f, 13.8f)
                verticalLineToRelative(-0.613f)
                horizontalLineToRelative(-0.587f)
                verticalLineToRelative(0.613f)
                horizontalLineToRelative(0.294f)
                close()
                moveTo(3.013f, 13.187f)
                lineTo(3.013f, 12.6f)
                lineTo(2.4f, 12.6f)
                verticalLineToRelative(0.587f)
                horizontalLineToRelative(0.307f)
                close()
                moveTo(2.4f, 12.6f)
                verticalLineToRelative(-0.613f)
                horizontalLineToRelative(-0.587f)
                verticalLineToRelative(0.613f)
                horizontalLineToRelative(0.294f)
                close()
                moveTo(1.813f, 11.987f)
                lineTo(1.813f, 11.4f)
                lineTo(1.2f, 11.4f)
                verticalLineToRelative(0.587f)
                horizontalLineToRelative(0.307f)
                close()
                moveTo(1.2f, 11.4f)
                verticalLineToRelative(-0.613f)
                lineTo(0.614f, 10.787f)
                verticalLineToRelative(0.613f)
                horizontalLineToRelative(0.293f)
                close()
                moveTo(0.614f, 10.787f)
                verticalLineToRelative(-9.6f)
                lineTo(0.0f, 1.187f)
                verticalLineToRelative(9.6f)
                horizontalLineToRelative(0.307f)
                close()
                moveTo(13.52f, 0.6f)
                verticalLineToRelative(0.293f)
                horizontalLineToRelative(1.493f)
                verticalLineToRelative(0.293f)
                horizontalLineToRelative(0.293f)
                lineTo(15.306f, 0.893f)
                horizontalLineToRelative(0.294f)
                lineTo(15.6f, 0.6f)
                horizontalLineToRelative(-1.04f)
                close()
                moveTo(15.013f, 1.186f)
                horizontalLineToRelative(-0.293f)
                verticalLineToRelative(0.32f)
                horizontalLineToRelative(0.293f)
                verticalLineToRelative(-0.16f)
                close()
                moveTo(14.72f, 1.506f)
                horizontalLineToRelative(-0.32f)
                lineTo(14.4f, 1.8f)
                horizontalLineToRelative(0.32f)
                verticalLineToRelative(-0.147f)
                close()
                moveTo(14.72f, 1.8f)
                verticalLineToRelative(0.293f)
                horizontalLineToRelative(0.293f)
                lineTo(15.013f, 1.8f)
                horizontalLineToRelative(-0.147f)
                close()
                moveTo(14.4f, 1.8f)
                horizontalLineToRelative(-0.294f)
                verticalLineToRelative(0.293f)
                horizontalLineToRelative(0.294f)
                verticalLineToRelative(-0.147f)
                close()
                moveTo(14.106f, 2.093f)
                horizontalLineToRelative(-0.293f)
                verticalLineToRelative(0.293f)
                horizontalLineToRelative(-0.293f)
                verticalLineToRelative(0.32f)
                horizontalLineToRelative(2.08f)
                verticalLineToRelative(-0.32f)
                horizontalLineToRelative(-1.494f)
                lineTo(14.106f, 2.24f)
                close()
                moveTo(14.4f, 1.506f)
                verticalLineToRelative(-0.32f)
                horizontalLineToRelative(-0.294f)
                verticalLineToRelative(0.32f)
                horizontalLineToRelative(0.147f)
                close()
                moveTo(16.506f, 1.8f)
                verticalLineToRelative(0.293f)
                horizontalLineToRelative(0.907f)
                verticalLineToRelative(0.293f)
                horizontalLineToRelative(0.293f)
                verticalLineToRelative(-0.293f)
                lineTo(18.0f, 2.093f)
                lineTo(18.0f, 1.8f)
                horizontalLineToRelative(-0.747f)
                close()
                moveTo(17.413f, 2.386f)
                horizontalLineToRelative(-0.293f)
                verticalLineToRelative(0.32f)
                horizontalLineToRelative(-0.614f)
                lineTo(16.506f, 3.0f)
                lineTo(18.0f, 3.0f)
                verticalLineToRelative(-0.294f)
                horizontalLineToRelative(-0.587f)
                verticalLineToRelative(-0.16f)
                close()
                moveTo(16.213f, 6.6f)
                verticalLineToRelative(0.293f)
                horizontalLineToRelative(0.586f)
                lineTo(16.799f, 6.6f)
                horizontalLineToRelative(-0.293f)
                close()
                moveTo(16.799f, 6.893f)
                verticalLineToRelative(0.293f)
                horizontalLineToRelative(0.907f)
                verticalLineToRelative(-0.293f)
                horizontalLineToRelative(-0.453f)
                close()
                moveTo(17.706f, 7.186f)
                verticalLineToRelative(0.32f)
                lineTo(18.0f, 7.506f)
                verticalLineToRelative(-0.32f)
                horizontalLineToRelative(-0.146f)
                close()
            }
        }
        .build()
        return _vencord!!
    }

private var _vencord: ImageVector? = null
