package com.woowla.compose.icon.collections.devicons.devicons.safari

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType.Companion.NonZero
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.woowla.compose.icon.collections.devicons.devicons.SafariGroup

public val SafariGroup.Plain: ImageVector
    get() {
        if (_plain != null) {
            return _plain!!
        }
        _plain = Builder(name = "Plain", defaultWidth = 128.0.dp, defaultHeight = 128.0.dp,
                viewportWidth = 128.0f, viewportHeight = 128.0f).apply {
            path(fill = SolidColor(Color(0xFF1B88CA)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = NonZero) {
                moveTo(64.0f, 1.5f)
                curveTo(29.5f, 1.5f, 1.5f, 29.5f, 1.5f, 64.0f)
                reflectiveCurveToRelative(28.0f, 62.5f, 62.5f, 62.5f)
                reflectiveCurveToRelative(62.5f, -28.0f, 62.5f, -62.5f)
                reflectiveCurveTo(98.5f, 1.5f, 64.0f, 1.5f)
                close()
                moveTo(120.0f, 59.4f)
                lineToRelative(-5.0f, 0.4f)
                lineToRelative(-0.1f, -1.0f)
                lineToRelative(5.0f, -0.4f)
                lineToRelative(0.1f, 1.0f)
                close()
                moveTo(120.0f, 63.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-9.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(9.0f)
                close()
                moveTo(119.4f, 54.6f)
                lineToRelative(-9.1f, 1.6f)
                lineToRelative(-0.2f, -1.0f)
                lineToRelative(9.1f, -1.6f)
                lineToRelative(0.2f, 1.0f)
                close()
                moveTo(118.4f, 49.8f)
                lineToRelative(-4.9f, 1.3f)
                lineToRelative(-0.3f, -1.0f)
                lineToRelative(4.9f, -1.3f)
                lineToRelative(0.3f, 1.0f)
                close()
                moveTo(117.0f, 45.1f)
                lineToRelative(-8.6f, 3.2f)
                lineToRelative(-0.3f, -0.9f)
                lineToRelative(8.6f, -3.2f)
                lineToRelative(0.3f, 0.9f)
                close()
                moveTo(115.2f, 40.5f)
                lineToRelative(-4.5f, 2.1f)
                lineToRelative(-0.4f, -0.9f)
                lineToRelative(4.5f, -2.1f)
                lineToRelative(0.4f, 0.9f)
                close()
                moveTo(112.9f, 36.2f)
                lineToRelative(-8.0f, 4.6f)
                lineToRelative(-0.5f, -0.9f)
                lineToRelative(8.0f, -4.6f)
                lineToRelative(0.5f, 0.9f)
                close()
                moveTo(109.8f, 31.2f)
                lineToRelative(0.6f, 0.8f)
                lineToRelative(-4.1f, 2.9f)
                lineToRelative(-0.6f, -0.8f)
                lineToRelative(4.1f, -2.9f)
                close()
                moveTo(107.4f, 28.1f)
                lineToRelative(-7.1f, 5.9f)
                lineToRelative(-0.6f, -0.8f)
                lineToRelative(7.1f, -5.9f)
                lineToRelative(0.6f, 0.8f)
                close()
                moveTo(100.5f, 21.1f)
                lineToRelative(-5.9f, 7.1f)
                lineToRelative(-0.8f, -0.6f)
                lineToRelative(5.9f, -7.1f)
                lineToRelative(0.8f, 0.6f)
                close()
                moveTo(95.8f, 17.5f)
                lineToRelative(0.8f, 0.6f)
                lineToRelative(-2.9f, 4.1f)
                lineToRelative(-0.8f, -0.6f)
                lineToRelative(2.9f, -4.1f)
                close()
                moveTo(92.6f, 15.4f)
                lineToRelative(-4.6f, 8.0f)
                lineToRelative(-0.9f, -0.5f)
                lineToRelative(4.6f, -8.0f)
                lineToRelative(0.9f, 0.5f)
                close()
                moveTo(87.3f, 12.7f)
                lineToRelative(0.9f, 0.4f)
                lineToRelative(-2.1f, 4.5f)
                lineToRelative(-0.9f, -0.4f)
                lineToRelative(2.1f, -4.5f)
                close()
                moveTo(82.8f, 10.9f)
                lineToRelative(0.9f, 0.3f)
                lineToRelative(-3.2f, 8.6f)
                lineToRelative(-0.9f, -0.3f)
                lineToRelative(3.2f, -8.6f)
                close()
                moveTo(78.1f, 9.4f)
                lineToRelative(1.0f, 0.3f)
                lineToRelative(-1.3f, 4.9f)
                lineToRelative(-1.0f, -0.3f)
                lineToRelative(1.3f, -4.9f)
                close()
                moveTo(73.3f, 8.4f)
                lineToRelative(1.0f, 0.2f)
                lineToRelative(-1.6f, 9.1f)
                lineToRelative(-1.0f, -0.2f)
                lineToRelative(1.6f, -9.1f)
                close()
                moveTo(68.4f, 7.8f)
                lineToRelative(1.0f, 0.1f)
                lineToRelative(-0.4f, 5.0f)
                lineToRelative(-1.0f, -0.1f)
                lineToRelative(0.4f, -5.0f)
                close()
                moveTo(63.0f, 8.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(9.0f)
                horizontalLineToRelative(-1.0f)
                lineTo(63.0f, 8.0f)
                close()
                moveTo(59.6f, 7.8f)
                lineToRelative(0.4f, 5.0f)
                lineToRelative(-1.0f, 0.1f)
                lineToRelative(-0.4f, -5.0f)
                lineToRelative(1.0f, -0.1f)
                close()
                moveTo(54.7f, 8.4f)
                lineToRelative(1.6f, 9.1f)
                lineToRelative(-1.0f, 0.2f)
                lineToRelative(-1.6f, -9.1f)
                lineToRelative(1.0f, -0.2f)
                close()
                moveTo(49.9f, 9.4f)
                lineToRelative(1.3f, 4.9f)
                lineToRelative(-1.0f, 0.3f)
                lineTo(49.0f, 9.7f)
                lineToRelative(0.9f, -0.3f)
                close()
                moveTo(45.2f, 10.9f)
                lineToRelative(3.2f, 8.6f)
                lineToRelative(-0.9f, 0.3f)
                lineToRelative(-3.2f, -8.6f)
                lineToRelative(0.9f, -0.3f)
                close()
                moveTo(40.7f, 12.7f)
                lineToRelative(2.1f, 4.5f)
                lineToRelative(-0.9f, 0.4f)
                lineToRelative(-2.1f, -4.5f)
                lineToRelative(0.9f, -0.4f)
                close()
                moveTo(36.3f, 14.9f)
                lineToRelative(4.6f, 8.0f)
                lineToRelative(-0.9f, 0.5f)
                lineToRelative(-4.6f, -8.0f)
                lineToRelative(0.9f, -0.5f)
                close()
                moveTo(32.2f, 17.5f)
                lineToRelative(2.9f, 4.1f)
                lineToRelative(-0.8f, 0.6f)
                lineToRelative(-2.9f, -4.1f)
                lineToRelative(0.8f, -0.6f)
                close()
                moveTo(28.3f, 20.5f)
                lineToRelative(5.9f, 7.1f)
                lineToRelative(-0.8f, 0.6f)
                lineToRelative(-5.9f, -7.1f)
                lineToRelative(0.8f, -0.6f)
                close()
                moveTo(24.6f, 23.7f)
                lineToRelative(3.5f, 3.5f)
                lineToRelative(-0.7f, 0.8f)
                lineToRelative(-3.5f, -3.5f)
                lineToRelative(0.7f, -0.8f)
                close()
                moveTo(21.2f, 27.3f)
                lineToRelative(7.1f, 5.9f)
                lineToRelative(-0.6f, 0.8f)
                lineToRelative(-7.1f, -5.9f)
                lineToRelative(0.6f, -0.8f)
                close()
                moveTo(18.2f, 31.2f)
                lineToRelative(4.1f, 2.9f)
                lineToRelative(-0.6f, 0.8f)
                lineToRelative(-4.1f, -2.9f)
                lineToRelative(0.6f, -0.8f)
                close()
                moveTo(15.6f, 35.3f)
                lineToRelative(8.0f, 4.6f)
                lineToRelative(-0.6f, 0.9f)
                lineToRelative(-8.0f, -4.6f)
                lineToRelative(0.6f, -0.9f)
                close()
                moveTo(13.3f, 39.6f)
                lineToRelative(4.5f, 2.1f)
                lineToRelative(-0.4f, 0.9f)
                lineToRelative(-4.5f, -2.1f)
                lineToRelative(0.4f, -0.9f)
                close()
                moveTo(11.4f, 44.2f)
                lineToRelative(8.6f, 3.2f)
                lineToRelative(-0.3f, 0.9f)
                lineToRelative(-8.7f, -3.2f)
                lineToRelative(0.4f, -0.9f)
                close()
                moveTo(9.8f, 48.8f)
                lineToRelative(4.9f, 1.3f)
                lineToRelative(-0.3f, 1.0f)
                lineToRelative(-4.9f, -1.3f)
                lineToRelative(0.3f, -1.0f)
                close()
                moveTo(8.7f, 53.6f)
                lineToRelative(9.1f, 1.6f)
                lineToRelative(-0.2f, 1.0f)
                lineToRelative(-9.1f, -1.6f)
                lineToRelative(0.2f, -1.0f)
                close()
                moveTo(8.0f, 58.5f)
                lineToRelative(5.0f, 0.4f)
                lineToRelative(-0.1f, 1.0f)
                lineToRelative(-5.0f, -0.4f)
                lineToRelative(0.1f, -1.0f)
                close()
                moveTo(17.0f, 63.0f)
                verticalLineToRelative(1.0f)
                lineTo(8.0f, 64.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(9.0f)
                close()
                moveTo(8.0f, 68.3f)
                lineToRelative(5.0f, -0.4f)
                lineToRelative(0.1f, 1.0f)
                lineToRelative(-5.0f, 0.4f)
                lineToRelative(-0.1f, -1.0f)
                close()
                moveTo(8.6f, 73.1f)
                lineToRelative(9.1f, -1.6f)
                lineToRelative(0.2f, 1.0f)
                lineToRelative(-9.1f, 1.6f)
                lineToRelative(-0.2f, -1.0f)
                close()
                moveTo(9.6f, 77.9f)
                lineToRelative(4.9f, -1.3f)
                lineToRelative(0.3f, 1.0f)
                lineToRelative(-4.9f, 1.3f)
                lineToRelative(-0.3f, -1.0f)
                close()
                moveTo(11.0f, 82.6f)
                lineToRelative(8.6f, -3.2f)
                lineToRelative(0.3f, 0.9f)
                lineToRelative(-8.6f, 3.2f)
                lineToRelative(-0.3f, -0.9f)
                close()
                moveTo(12.8f, 87.2f)
                lineToRelative(4.5f, -2.1f)
                lineToRelative(0.4f, 0.9f)
                lineToRelative(-4.5f, 2.1f)
                lineToRelative(-0.4f, -0.9f)
                close()
                moveTo(15.1f, 91.6f)
                lineToRelative(8.0f, -4.6f)
                lineToRelative(0.5f, 0.9f)
                lineToRelative(-8.0f, 4.6f)
                lineToRelative(-0.5f, -0.9f)
                close()
                moveTo(18.2f, 96.5f)
                lineToRelative(-0.6f, -0.8f)
                lineToRelative(4.1f, -2.9f)
                lineToRelative(0.6f, 0.8f)
                lineToRelative(-4.1f, 2.9f)
                close()
                moveTo(27.7f, 93.7f)
                lineToRelative(0.6f, 0.8f)
                lineToRelative(-7.1f, 5.9f)
                lineToRelative(-0.6f, -0.8f)
                lineToRelative(7.1f, -5.9f)
                close()
                moveTo(27.5f, 106.6f)
                lineToRelative(5.9f, -7.1f)
                lineToRelative(0.8f, 0.6f)
                lineToRelative(-5.9f, 7.1f)
                lineToRelative(-0.8f, -0.6f)
                close()
                moveTo(32.2f, 110.2f)
                lineToRelative(-0.8f, -0.6f)
                lineToRelative(2.9f, -4.1f)
                lineToRelative(0.8f, 0.6f)
                lineToRelative(-2.9f, 4.1f)
                close()
                moveTo(35.4f, 112.3f)
                lineToRelative(4.6f, -8.0f)
                lineToRelative(0.9f, 0.5f)
                lineToRelative(-4.6f, 8.0f)
                lineToRelative(-0.9f, -0.5f)
                close()
                moveTo(40.7f, 115.0f)
                lineToRelative(-0.9f, -0.4f)
                lineToRelative(2.1f, -4.5f)
                lineToRelative(0.9f, 0.4f)
                lineToRelative(-2.1f, 4.5f)
                close()
                moveTo(45.2f, 116.9f)
                lineToRelative(-0.9f, -0.3f)
                lineToRelative(3.2f, -8.6f)
                lineToRelative(0.9f, 0.3f)
                lineToRelative(-3.2f, 8.6f)
                close()
                moveTo(49.9f, 118.3f)
                lineToRelative(-1.0f, -0.3f)
                lineToRelative(1.3f, -4.9f)
                lineToRelative(1.0f, 0.3f)
                lineToRelative(-1.3f, 4.9f)
                close()
                moveTo(54.7f, 119.3f)
                lineToRelative(-1.0f, -0.2f)
                lineToRelative(1.6f, -9.1f)
                lineToRelative(1.0f, 0.2f)
                lineToRelative(-1.6f, 9.1f)
                close()
                moveTo(59.6f, 119.9f)
                lineToRelative(-1.0f, -0.1f)
                lineToRelative(0.4f, -5.0f)
                lineToRelative(1.0f, 0.1f)
                lineToRelative(-0.4f, 5.0f)
                close()
                moveTo(64.0f, 120.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-9.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(9.0f)
                close()
                moveTo(68.4f, 119.9f)
                lineToRelative(-0.4f, -5.0f)
                lineToRelative(1.0f, -0.1f)
                lineToRelative(0.4f, 5.0f)
                lineToRelative(-1.0f, 0.1f)
                close()
                moveTo(21.0f, 106.7f)
                lineToRelative(37.7f, -48.0f)
                lineToRelative(48.0f, -37.7f)
                lineToRelative(-36.8f, 48.9f)
                lineTo(21.0f, 106.7f)
                close()
                moveTo(73.3f, 119.3f)
                lineToRelative(-1.6f, -9.1f)
                lineToRelative(1.0f, -0.2f)
                lineToRelative(1.6f, 9.1f)
                lineToRelative(-1.0f, 0.2f)
                close()
                moveTo(78.1f, 118.3f)
                lineToRelative(-1.3f, -4.9f)
                lineToRelative(1.0f, -0.3f)
                lineTo(79.0f, 118.0f)
                lineToRelative(-0.9f, 0.3f)
                close()
                moveTo(82.8f, 116.9f)
                lineToRelative(-3.2f, -8.6f)
                lineToRelative(0.9f, -0.3f)
                lineToRelative(3.2f, 8.6f)
                lineToRelative(-0.9f, 0.3f)
                close()
                moveTo(87.3f, 115.0f)
                lineToRelative(-2.1f, -4.5f)
                lineToRelative(0.9f, -0.4f)
                lineToRelative(2.1f, 4.5f)
                lineToRelative(-0.9f, 0.4f)
                close()
                moveTo(91.7f, 112.8f)
                lineToRelative(-4.6f, -8.0f)
                lineToRelative(0.9f, -0.5f)
                lineToRelative(4.6f, 8.0f)
                lineToRelative(-0.9f, 0.5f)
                close()
                moveTo(95.8f, 110.2f)
                lineToRelative(-2.9f, -4.1f)
                lineToRelative(0.8f, -0.6f)
                lineToRelative(2.9f, 4.1f)
                lineToRelative(-0.8f, 0.6f)
                close()
                moveTo(99.7f, 107.3f)
                lineToRelative(-5.9f, -7.1f)
                lineToRelative(0.8f, -0.6f)
                lineToRelative(5.9f, 7.1f)
                lineToRelative(-0.8f, 0.6f)
                close()
                moveTo(103.4f, 104.0f)
                lineToRelative(-3.5f, -3.5f)
                lineToRelative(0.7f, -0.7f)
                lineToRelative(3.5f, 3.5f)
                lineToRelative(-0.7f, 0.7f)
                close()
                moveTo(106.8f, 100.4f)
                lineToRelative(-7.1f, -5.9f)
                lineToRelative(0.6f, -0.8f)
                lineToRelative(7.1f, 5.9f)
                lineToRelative(-0.6f, 0.8f)
                close()
                moveTo(109.8f, 96.5f)
                lineToRelative(-4.1f, -2.9f)
                lineToRelative(0.6f, -0.8f)
                lineToRelative(4.1f, 2.9f)
                lineToRelative(-0.6f, 0.8f)
                close()
                moveTo(112.4f, 92.4f)
                lineToRelative(-8.0f, -4.6f)
                lineToRelative(0.5f, -0.9f)
                lineToRelative(8.0f, 4.6f)
                lineToRelative(-0.5f, 0.9f)
                close()
                moveTo(114.7f, 88.1f)
                lineToRelative(-4.5f, -2.1f)
                lineToRelative(0.4f, -0.9f)
                lineToRelative(4.5f, 2.1f)
                lineToRelative(-0.4f, 0.9f)
                close()
                moveTo(116.6f, 83.6f)
                lineToRelative(-8.6f, -3.2f)
                lineToRelative(0.3f, -0.9f)
                lineToRelative(8.6f, 3.2f)
                lineToRelative(-0.3f, 0.9f)
                close()
                moveTo(118.2f, 78.9f)
                lineToRelative(-4.9f, -1.3f)
                lineToRelative(0.3f, -1.0f)
                lineToRelative(4.9f, 1.3f)
                lineToRelative(-0.3f, 1.0f)
                close()
                moveTo(119.3f, 74.1f)
                lineToRelative(-9.1f, -1.6f)
                lineToRelative(0.2f, -1.0f)
                lineToRelative(9.1f, 1.6f)
                lineToRelative(-0.2f, 1.0f)
                close()
                moveTo(120.0f, 69.3f)
                lineToRelative(-5.0f, -0.4f)
                lineToRelative(0.1f, -1.0f)
                lineToRelative(5.0f, 0.4f)
                lineToRelative(-0.1f, 1.0f)
                close()
            }
        }
        .build()
        return _plain!!
    }

private var _plain: ImageVector? = null
