name: Update icons

on:
  push:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-icons:
    name: Update icons
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: gradle/actions/wrapper-validation@v3
      - name: Create branch
        id: create-branch
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          timestamp=$(date +"%Y-%m-%d-%H-%M-%S")
          git checkout -b "update-icons-$timestamp"
      - name: Update
        run: ./gradlew octicons:download-icons remix:download-icons tabler:download-icons -Pgitcommit --no-parallel
      - name: Create pull request
        # https://github.com/peter-evans/create-pull-request/releases/tag/v7.0.5
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f
        with:
          title: Update icons