name: Update icons

on:
  push:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-icons:
    name: Update icons
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: gradle/actions/wrapper-validation@v3
      - name: Create branch
        id: create-branch
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          timestamp=$(date +"%Y-%m-%d-%H-%M-%S")
          branch_name="update-icons-$timestamp"
          echo "branch=$branch_name" >> $GITHUB_OUTPUT
          git checkout -b "$branch_name"
      - name: Download icons
        run: ./gradlew octicons:download-icons remix:download-icons tabler:download-icons --no-parallel
      - name: Create pull request if changes exist
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "There are changes"
            git add --all
            git commit -m "Update icons"
            git push origin ${{ steps.create-branch.outputs.branch }}
            gh pr create --title "Update icons" --body "Update icons"
          else
            echo "There are no changes"
          fi