name: Update icons

on:
  push:

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: gradle/actions/wrapper-validation@v3
      - name: Create branch
        id: create-branch
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          timestamp=$(date +"%Y-%m-%d-%H-%M-%S")
          git checkout -b "update-icons-$timestamp"
      - name: Update
        run: ./gradlew octicons:download-icons remix:download-icons tabler:download-icons -Pgitcommit --no-parallel --no-configuration-cache
      - name: Create pull request
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          non_pushed_commits=$(git log origin/$current_branch..HEAD --oneline)
          if [ -z "$non_pushed_commits" ]; then
            echo "There are no changes"
          else
            echo "There are changes"
            gh pr create --title "Update icons" --body "Update icons"
          fi