name: Update icons

on:
  push:

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: gradle/actions/wrapper-validation@v3
      - name: Create branch
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          timestamp=$(date +"%Y-%m-%d-%H-%M-%S")
          git checkout -b "update-icons-$timestamp"
      - name: Update
        run: ./gradlew octicons:download-icons remix:download-icons tabler:download-icons -Pgitcommit --no-parallel --no-configuration-cache
      - name: Create pull request
        shell: bash
        run: |
          git diff
          if [[ `git status --porcelain` ]]; then
            echo "There are changes"
          else
            echo "There are no changes"
          fi
