name: Update icons

on:
  push:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-icons:
    name: Update icons
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: gradle/actions/wrapper-validation@v3
      - name: Create branch
        id: create-branch
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          timestamp=$(date +"%Y-%m-%d-%H-%M-%S")
          branch_name="update-icons-$timestamp"
          git checkout -b "$branch_name"
      - name: Update
        run: ./gradlew octicons:download-icons remix:download-icons tabler:download-icons -Pgitcommit --no-parallel
      - name: Check for changes
        id: check-changes
        shell: bash
        run: |
          non_pushed_commits=$(git log origin/$(git rev-parse --abbrev-ref HEAD)..HEAD --oneline)
          echo "non_pushed_commits=$non_pushed_commits" >> "$GITHUB_OUTPUT"
      - name: Push branch if changes exist
        if: steps.check-changes.outputs.non_pushed_commits != ''
        shell: bash
        run: |
          git push origin HEAD
      - name: Create pull request if changes exist
        if: steps.check-changes.outputs.non_pushed_commits != ''
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "Update icons" --body "Update icons"